insert into departments (name, address_line_one, town, post_code) values ('Finance', '23 High Street', 'Edinburgh', 'EH1 1JH')
insert into departments (name, address_line_one, town, post_code) values ('Sales', '55 Main Street', 'Edinburgh', 'EH1 4HG')
insert into departments (name, address_line_one, town, post_code) values ('IT Support', '121 Gordon Street', 'Glasgow', 'G21 5RD')
insert into departments (name, address_line_one, town, post_code) values ('Facilities Management', '15 James Street', 'Aberdeen', 'AB1 7HY')

insert into users (forename, surname, email_address, phone_number, address_line_one, town, post_code, department_id) values ('Alan','Smith', 'alan@smith.net', '0131 325 2521','12 James Street','Edinburgh', 'EH6 7TG', 1)
insert into users (forename, surname, email_address, phone_number, address_line_one, town, post_code, department_id) values ('Alan','Jones', 'alan@jones.net', '0141 325 2521','12 James Street','Glasgow', 'G21 7TG', 2)
insert into users (forename, surname, email_address, phone_number, address_line_one, town, post_code, department_id) values ('Kenny','Smith', 'kenny@smith.net', '01224 325 2521','12 James Street','Aberdeen', 'AB3 1HG', 3)
insert into users (forename, surname, email_address, phone_number, address_line_one, town, post_code, department_id) values ('Jane','Kennedy', 'jane@kennedy.net', '0141 325 2521','12 James Street','Glasgow', 'G54 8HY', 1)
insert into users (forename, surname, email_address, phone_number, address_line_one, town, post_code, department_id) values ('Deborah','James', 'deborah@james.net', '0131 325 2521','12 James Street','Edinburgh', 'EH6 7TG', 2)
insert into users (forename, surname, email_address, phone_number, address_line_one, town, post_code, department_id) values ('Susan','Urquhart', 'susan@urquhart.net', '01224 325 2521','12 James Street','Aberdeen', 'AB2 7TG', 3)
insert into users (forename, surname, email_address, phone_number, address_line_one, town, post_code, department_id) values ('William','Goodwin', 'william@goodwin.net', '0131 325 2521','12 James Street','Edinburgh', 'EH6 7TG', 4)
insert into users (forename, surname, email_address, phone_number, address_line_one, town, post_code, department_id) values ('Andrew','Johnson', 'andrew@johnson.net', '0141 325 2521','12 James Street','Glasgow', 'G32 7TG', 2)
insert into users (forename, surname, email_address, phone_number, address_line_one, town, post_code, department_id) values ('Graeme','Kennedy', 'graeme@kennedy.net', '01224 325 2521','12 James Street','Aberdeen', 'AB1 1HG', 2)
insert into users (forename, surname, email_address, phone_number, address_line_one, town, post_code, department_id) values ('June','Jackson', 'june@jackson.net', '0131 325 2521','12 James Street','Edinburgh', 'EH6 8UJ', 4)
